keys:
  - &admin_air age1555na6yxk4c4p4zr0s228vue4hwm3jn7kup47m4pesue39xq3elsjlcyvh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_air
